server:
  port: 8081
spring:
  application:
    name: hmdp
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.hmdp.entity
  configuration:
    map-underscore-to-camel-case: true
