---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2026/3/12 15:04
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('DEL', KEYS[1])
end
return 0